### ISSUE TITLE
Can't access link to test case in a new tab

### ISSUE THREAD

**Issue by PicoleDeLimao** [SAP/InfraBox#256] opened 2019-01-22 16:45 UTC
Open a task, click in the "tests" tab and copy the link to any test case. If you try to paste it in a new tab, you can't access its content, as you can only see the Infrabox menu and nothing else, as shown below.

https://imgur.com/a/If0OMpy

**Comment by ib-steffen** [comment] 2019-01-28 10:49
I cannot reproduce the issue. please contact me on slack. For now I'll close the issue.

**Closed by ib-steffen** 2019-01-28 10:49 UTC
